apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer # Expose the frontend externally
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 80 # The port the LoadBalancer listens on
    targetPort: 80 # The NGINX port inside the container
