apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer # Using LoadBalancer to expose externally for testing. Change to ClusterIP if using an Ingress.
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
